language: cpp

services:
  - docker

sudo: required
dist: trusty
osx_image: xcode11

env:
  global:
    - QDEP_CACHE_DIR=$HOME/.qdep-cache
    - QT_VER=5.13.2
    - DOCKER_IMAGE=base
    - MAKE_RUN_TESTS=true
    - TARGET_NAME=qtapng

matrix:
  include:
    - os: linux
      env:
        - PLATFORM=gcc_64
        # - BUILD_DOC=true
        - BUILD_EXAMPLES=true
    - os: linux
      env:
        - PLATFORM=android_arm64_v8a
    - os: linux
      env:
        - PLATFORM=android_x86_64
    - os: linux
      env:
        - PLATFORM=android_armv7
    - os: linux
      env:
        - PLATFORM=android_x86
    - os: linux
      env:
        - PLATFORM=wasm_32
    - os: osx
      env:
        - PLATFORM=clang_64
    - os: osx
      env:
        - PLATFORM=ios

install:
  - git clone https://github.com/Skycoder42/QtModules.git ./qtmodules-travis
  - travis_wait 40 ./qtmodules-travis/ci/$TRAVIS_OS_NAME/setup.sh

script:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then sudo chmod -R a+rwx /opt/qt/$QT_VER/$PLATFORM/plugins/imageformats; fi
  - ./qtmodules-travis/ci/$TRAVIS_OS_NAME/build.sh

before_deploy:
  - ./qtmodules-travis/ci/$TRAVIS_OS_NAME/upload-prepare.sh
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: rcdY0c8fX3oxFqMLGGBiAt7Dv4M/eJsHLCPYAE9V/ItEzbvGvnUnoAsZXBEZszTgIeIGqTcIjnYnmQ0dl4f54dDfeW29DAiurpWT+dZ228A1SyFD7FVz1PzSbtagHLdaV2cWT/ez8wKWgEyEVDEgam7o2O0O+W91jQZO74YEYfHmj+Hro0C3fMqFXDwY7phL/G1MGY9P2lwU0Uoo+0OrV/42RhjFoKPG7kN2RMd/Z91jlhWyBQZvBQZ9aOiGQyRe0Y9tNjnhpSbuEbZp/jSlR62Nf0ZGmCm0lSxtH/G1Y/l4bzvknHvP4k0hg91E93IQLbSkuXCOeVa3/ghgN0m9gL+S1OVGOOftEeXQOCVI14IMkmv0vC5VdzfVY/dIFwFJG20uLylFEz/RupLZEmg7JONUJvbJYl5ABP9End2HScM2E+GDlvSHeoPbSX2hcKqcxZy5mIWdc5ie7s4m/ft1aRAryMEwGf3TbwMQRC8oLkJ9p3COPKPqKwqolLHv4wR1ei7p2caldtygfcv/JEK+jZwyox6m8YJkcI4D1rolNGmXCt1Btn1BkotH9p6oHsG18unspcY+r2IZVNhM+INegOnlzMRku0WoEuh02Qrv79lKfQ8Kw4sZhhL58Iy/K/7rQ8hM2fH+ODb5OT6w4htRolimkMV9HOsDjLPqc2u8h+A=
  file_glob: true
  file: install/${TARGET_NAME}_*_$QT_VER.tar.xz
  on:
    repo: Skycoder42/QtApng
    tags: true

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
    - $QDEP_CACHE_DIR
